In [9]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_excel(r"C:\Users\anchsingh\Anchal Singh\Data Analysis with Python\Salary_Data.xlsx")

#Numpy Part 1

In [11]:
#Numpy Part 1
#Create an Array (numpy.array(object))

x=np.array([2,3,4,5])
x

array([2, 3, 4, 5])

In [8]:
print(type(x))

<class 'numpy.ndarray'>


In [12]:
print(x)

[2 3 4 5]


In [13]:
#Numpy can handle Categorical entities

x=np.array([2,3,'n',5])

In [14]:
print(x)

['2' '3' 'n' '5']


In [17]:
#Generate arrays using linspace()
#numpy.linspace()
#numpy.linspace(start,stop,num,dtype,retstep)

In [22]:
b=np.linspace(start=1,
              stop=5,
              num=10,
              endpoint=True,
              retstep=False)

In [23]:
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [24]:
b=np.linspace(start=1,
              stop=5,
              num=10,
              endpoint=True,
              retstep=True)

In [25]:
print(b)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), np.float64(0.4444444444444444))


In [26]:
#arange()
#numpy.arrange(start,stop,step)

np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [29]:
#numpy.ones()
#numpy.ones(shape,dtype)

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
#numpy.zeros()
#numpy.zeros(shape,dtype)

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#random.rand()

#numpy.random.rand()

np.random.rand(5)

array([0.13078961, 0.11596997, 0.9400635 , 0.93737683, 0.73675079])

In [34]:
np.random.rand(5,2)

array([[0.44775447, 0.23821491],
       [0.70075238, 0.6160251 ],
       [0.02139521, 0.59916235],
       [0.81426719, 0.6265785 ],
       [0.04872784, 0.66064201]])

In [35]:
#Generate arrays using lodspace
#numpy.logspace()
#numpy.logspace(start,stop,num,endpoint,base,dtype)
np.logspace(1,10,num=5,endpoint=True,base=10.0)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [39]:
#timeit - execution time
#Array works faster than List 
#LIST
x=range(50)

In [40]:
timeit sum(x)

284 ns ± 1.54 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [41]:
#Array

y=np.array(x)

In [42]:
timeit np.sum(y)

2.65 μs ± 33.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [45]:
#getsizeof()  - returns the size of objects
#size of list can be found by multiplying size of indiv element with no of elements in the list.
import sys
# sys.getsizeof(object)

sys.getsizeof(1)*len(x)


1400

In [46]:
#numpy.ndarray.itemsize -  
#same as list for array
y.itemsize*y.size

400

#Numpy Part 2

In [47]:
#Reshaping an array

In [50]:
#reshape()

grid=np.arange(start=1,stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
#Array Dimensions

a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])


In [54]:
a.shape

(3, 3)

In [55]:
#numpy.sum(array,axis)

np.sum(a)

np.int64(45)

In [56]:
a.sum()

np.int64(45)

In [57]:
#calculate sum along with the column (axis=0)
np.sum(a,axis=0)

array([12, 15, 18])

In [58]:
#calculate sum along with the row (axis=1)
np.sum(a,axis=1)

array([ 6, 15, 24])

In [67]:
#Numpy Addition
#numpy.add()
#numpy.add(array_1,array_2)

a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [60]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [61]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [62]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.remainder(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [69]:
#Accessing elements
a[1,2]

np.int64(6)

In [74]:
#acceesing 2 and 3 row
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [71]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
#1st row
a[0,:]

array([1, 2, 3])

In [76]:
#Subset of Array
#1st two rows and columns

a_sub=a[:2,:2]

In [77]:
a_sub

array([[1, 2],
       [4, 5]])

In [80]:
#updating values of array
a_sub[0,0]=12

In [81]:
a_sub

array([[12,  2],
       [ 4,  5]])

In [82]:
#Modifying subset will automatically update the subset
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [83]:
#Modifying array using transpose()
#numpy.transpose()

np.transpose(a)

array([[12,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [84]:
#Modify array using Append()
#append()
#numpy.append(array,axis)
a_row=np.append(a,[[10,11,14]],axis=0)

print(a_row)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 14]]


In [87]:
#Modifying array using append()

col=np.array([21,22,23]).reshape(3,1)
print(col)

[[21]
 [22]
 [23]]


In [89]:
#Modifying array using insert()
#insert() - add values at a given position and axis

#numpy.insert(array,obj,values,axis)

a_ins=np.insert(a,1,[14,12,56],axis=0)
print(a_ins)

[[12  2  3]
 [14 12 56]
 [ 4  5  6]
 [ 7  8  9]]
